os: linux
dist: jammy

jobs:
  include:
    - name: "job one"
      vm: 
        create:
          name: 27june_200k23_02
      script: 
        - echo "condition with job testkjestt"
        - echo $TRAVIS_COMMIT_MESSAGE
        - sleep 50
